# tomcat
server:
    port: 9090
# 多数据源用法，同spring-boot2-mysql-multi-datasource项目一样
spring:
    profiles: dev
    cloud:
        nacos:
          discovery:
            server-addr: localhost:8848
            namespace: ${spring.profiles.active}
          config:
            server-addr: localhost:8848
            namespace: ${spring.profiles.active}
            prefix: ${spring.application.name}
            file-extension: yml
            #shared-dataids: shareconfig1.yml,shareconfig2.yml
            #refreshable-dataids: shareconfig1.yml,shareconfig2.yml
             # 支持多个共享 Data Id 的配置，优先级小于extension-configs,自定义 Data Id 配置 属性是个集合，内部由 Config POJO 组成。Config 有 3 个属性，分别是 dataId, group 以及 refresh
            shared-configs[0]:
              data-id: shareconfig1.yml # 配置文件名-Data Id
              group: MAJUN_GROUP   # 默认为DEFAULT_GROUP
              refresh: false   # 是否动态刷新，默认为false
            shared-configs[1]:
              data-id: shareconfig2.yml
              group: MAJUN_GROUP
              refresh: true
    datasource:
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/db1?autoReconnect=true&useunicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
       username: root
       password: root
myname: ${spring.application.name}