# 不同的环境使用不同的配置，通过指定启动参数使用不同的profile和配置文件，比如：
# 开发环境：java -jar xxx.jar --spring.profiles.active=dev
# 生产环境：java -jar xxx.jar --spring.profiles.active=prod
spring:
    application:
        name: spring-boot-majun
   profiles:
      active: ${profile}
    cloud:
        nacos:
          discovery:
            server-addr: ${nacos_addr}
            namespace: ${spring.profiles.active}
          config:
            server-addr: ${nacos_addr}
            namespace: ${spring.profiles.active}
            prefix: ${spring.application.name}
            file-extension: yml
            #shared-dataids: shareconfig1.yml,shareconfig2.yml
            #refreshable-dataids: shareconfig1.yml,shareconfig2.yml
             # 支持多个共享 Data Id 的配置，优先级小于extension-configs,自定义 Data Id 配置 属性是个集合，内部由 Config POJO 组成。Config 有 3 个属性，分别是 dataId, group 以及 refresh
            shared-configs[0]:
              data-id: shareconfig1.yml # 配置文件名-Data Id
              group: MAJUN_GROUP   # 默认为DEFAULT_GROUP
              refresh: false   # 是否动态刷新，默认为false
            shared-configs[1]:
              data-id: shareconfig2.yml
              group: MAJUN_GROUP
              refresh: true
# mybatis
mybatis:
   config-location: classpath:mybatis-config.xml
   
# logging
logging:
   config: classpath:logback-${spring.profiles.active}.xml